version: "3.7"
services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
